In [17]:
from __future__ import print_function
import tensorflow as tf
import numpy as np

# create data
x_data = np.random.rand(100).astype(np.float32)
y_data = x_data*0.1 + 0.3

### create tensorflow structure start ###
Weights = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
biases = tf.Variable(tf.zeros([1]))

y = Weights*x_data + biases

loss = tf.reduce_mean(tf.square(y-y_data))
optimizer = tf.train.GradientDescentOptimizer(0.5)
train = optimizer.minimize(loss)

init = tf.initialize_all_variables()
### create tensorflow structure end ###

sess = tf.Session()
sess.run(init)          # Very important

for step in range(201):
    sess.run(train)
    if step % 20 == 0:
        print(step, sess.run(Weights), sess.run(biases))

0 [-0.00547561] [ 0.5327462]
20 [ 0.04869606] [ 0.32964587]
40 [ 0.08536898] [ 0.30845451]
60 [ 0.09582748] [ 0.30241111]
80 [ 0.09881009] [ 0.30068761]
100 [ 0.09966068] [ 0.30019608]
120 [ 0.09990323] [ 0.30005592]
140 [ 0.0999724] [ 0.30001596]
160 [ 0.09999214] [ 0.30000457]
180 [ 0.09999777] [ 0.30000129]
200 [ 0.09999937] [ 0.30000037]


In [7]:
# View more python tutorial on my Youtube and Youku channel!!!

# Youtube video tutorial: https://www.youtube.com/channel/UCdyjiB5H8Pu7aDTNVXTTpcg
# Youku video tutorial: http://i.youku.com/pythontutorial

"""
Please note, this code is only for python 3+. If you are using python 2+, please modify the code accordingly.
"""
from __future__ import print_function
import tensorflow as tf
from tensorflow.examples.tutorials.mnist import input_data
# number 1 to 10 data
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

def compute_accuracy(v_xs, v_ys):
    global prediction
    y_pre = sess.run(prediction, feed_dict={xs: v_xs, keep_prob: 1})
    correct_prediction = tf.equal(tf.argmax(y_pre,1), tf.argmax(v_ys,1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
    result = sess.run(accuracy, feed_dict={xs: v_xs, ys: v_ys, keep_prob: 1})
    return result

def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.1, shape=shape)
    return tf.Variable(initial)

def conv2d(x, W):
    # stride [1, x_movement, y_movement, 1]
    # Must have strides[0] = strides[3] = 1
    return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')

def max_pool_2x2(x):
    # stride [1, x_movement, y_movement, 1]
    return tf.nn.max_pool(x, ksize=[1,2,2,1], strides=[1,2,2,1], padding='SAME')

# define placeholder for inputs to network
xs = tf.placeholder(tf.float32, [None, 784]) # 28x28
ys = tf.placeholder(tf.float32, [None, 10])
keep_prob = tf.placeholder(tf.float32)
x_image = tf.reshape(xs, [-1, 28, 28, 1])
# print(x_image.shape)  # [n_samples, 28,28,1]

## conv1 layer ##
W_conv1 = weight_variable([5,5, 1,32]) # patch 5x5, in size 1, out size 32
b_conv1 = bias_variable([32])
h_conv1 = tf.nn.relu(conv2d(x_image, W_conv1) + b_conv1) # output size 28x28x32
h_pool1 = max_pool_2x2(h_conv1)                                         # output size 14x14x32

## conv2 layer ##
W_conv2 = weight_variable([5,5, 32, 64]) # patch 5x5, in size 32, out size 64
b_conv2 = bias_variable([64])
h_conv2 = tf.nn.relu(conv2d(h_pool1, W_conv2) + b_conv2) # output size 14x14x64
h_pool2 = max_pool_2x2(h_conv2)                                         # output size 7x7x64

## func1 layer ##
W_fc1 = weight_variable([7*7*64, 1024])
b_fc1 = bias_variable([1024])
# [n_samples, 7, 7, 64] ->> [n_samples, 7*7*64]
h_pool2_flat = tf.reshape(h_pool2, [-1, 7*7*64])
h_fc1 = tf.nn.relu(tf.matmul(h_pool2_flat, W_fc1) + b_fc1)
h_fc1_drop = tf.nn.dropout(h_fc1, keep_prob)

## func2 layer ##
W_fc2 = weight_variable([1024, 10])
b_fc2 = bias_variable([10])
prediction = tf.nn.softmax(tf.matmul(h_fc1_drop, W_fc2) + b_fc2)


# the error between prediction and real data
cross_entropy = tf.reduce_mean(-tf.reduce_sum(ys * tf.log(prediction),
                                              reduction_indices=[1]))       # loss
train_step = tf.train.AdamOptimizer(1e-4).minimize(cross_entropy)

sess = tf.Session()
# important step
sess.run(tf.initialize_all_variables())


batch_xs, batch_ys = mnist.train.next_batch(100)
#print(mnist.train.next_batch(100))


for i in range(1000):
    #print(mnist.train.next_batch)
    
    batch_xs, batch_ys = mnist.train.next_batch(100)
    
    print(batch_ys)
    #sess.run(train_step, feed_dict={xs: batch_xs, ys: batch_ys, keep_prob: 0.5})
    #if i % 50 == 0:
        #print(compute_accuracy(
          #mnist.test.images, mnist.test.labels))

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
[[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  1.  0.  0.  0

KeyboardInterrupt: 

In [5]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
from sklearn import cross_validation
import tensorflow as tf

In [6]:
trainData=np.genfromtxt('train.csv',delimiter=',')
testData=np.genfromtxt('test.csv',delimiter=',')
trainingPixmaps=trainData[0:35000,9:438]
trainingClasses=trainData[0:35000,1]
testPixmaps = testData[35001:49999,9:438]
testClasses=testData[35001:49999,1]

In [9]:
def compute_accuracy(v_xs, v_ys):
    global prediction
    y_pre = sess.run(prediction, feed_dict={xs: v_xs, keep_prob: 1})
    correct_prediction = tf.equal(tf.argmax(y_pre,1), tf.argmax(v_ys,1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
    result = sess.run(accuracy, feed_dict={xs: v_xs, ys: v_ys, keep_prob: 1})
    return result

def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial)

def bias_variable(shape):
    initial = tf.constant(0.1,shape = shape)
    return tf.Variable(initial)

#x is hte value of the image, W is the corresponding weight
def conv2d(x,W):
    #stride [1,x_movement,y_movement,1]
    #must have strides[0] and strides[3] =1 
    #which is stride [1,,,1] 
    return tf.nn.conv2d(x,W,strides=[1,1,1,1],padding = 'SAME')

def max_pool_2x2(x):
    #x is the output from conv2d
    #reduce the size from conv2d
    #stride [1,x_movement,y_movement,1]
    return tf.nn.max_pool(x,ksize=[1,2,2,1],strides=[1,2,2,1],padding = 'SAME')

In [14]:
#define placeholder for inputs to network
#13x33
xs = tf.placeholder(tf.float32,[None,429])
#98 classes
ys = tf.placeholder(tf.float32,[None,98]) 
#for drop out
keep_prob = tf.placeholder(tf.float32)

#1 means the image is black and white.if its colourful it needs to change
#to 3 for RGB
#-1 means the dimention. we dont care it now. we will update later
x_image = tf.reshape(xs,[-1,13,33,1])



##conv1 layer##
#1 means the image sickness which is 1 in our case
#dont know how to comput patch size(5x5) and height(32)
#need to research or ask!!
W_conv1 = weight_variable([2,2,1,32])
b_conv1 = bias_variable([32])
#relu means make it not linear
#hidden layer
h_conv1 = tf.nn.relu(conv2d(x_image,W_conv1) + b_conv1)#outpu size 13x33x32 because SAME padding
#pooling process
#hidden layer
h_pool1 = max_pool_2x2(h_conv1)#output size not sure7x17x32


##conv2 layer##
#1 means the image sickness which is 1 in our case
#dont know how to comput patch size(5x5) and height(32)
#need to research or ask!!
W_conv2 = weight_variable([2,2,32,64])
b_conv2 = bias_variable([64])
#relu means make it not linear
#hidden layer
h_conv2 = tf.nn.relu(conv2d(h_pool1,W_conv2) + b_conv2)#outpu size 13x33x64 because SAME padding
#pooling process
#hidden layer
h_pool2 = max_pool_2x2(h_conv2)#output size not sure4x9x64


##func1 lyaer##
W_fuc1 = weight_variable([4*9*64,1024])
b_fuc1 = bias_variable([1024])

h_pool2_flat = tf.reshape(h_pool2,[-1,4*9*64])
h_fuc1 = tf.nn.relu(tf.matmul(h_pool2_flat,W_fuc1)+b_fuc1)

#overfitting
h_fc1_drop = tf.nn.dropout(h_fc1,keep_prob)

##func2 lyaer##
W_fuc1 = weight_variable([1024,98])
b_fuc1 = bias_variable([98])
prediction = tf.nn.softmax(tf.matmul(h_fc1_drop,W_fuc1)+b_fuc1)

# the error between prediction and real data
cross_entropy = tf.reduce_mean(-tf.reduce_sum(ys * tf.log(prediction),
                                              reduction_indices=[1]))       # loss
train_step = tf.train.AdamOptimizer(1e-4).minimize(cross_entropy)



sess = tf.Session()
# important step
sess.run(tf.initialize_all_variables())


def data(number): 
    zeros = np.zeros(98)
    zeros[number] = number
    return zeros


#print(classes)
batch_xs = trainingPixmaps
batch_ys = trainingClasses
batch_ys_int = map(int,batch_ys)

list = []
for elem in batch_ys_int:
    list.append(data(elem))

afterlist = []  
for array in list:
    afterlist.append(map(float,array))
#batch_ys_float = map(float,list)
#print(batch_xs)


batch_ys1 = testClasses
batch_ys1_int = map(int,batch_ys1)

list1 = []
for elem in batch_ys1_int:
    list.append(data(elem))
    
afterlist1 = []
for array in list:
    afterlist1.append(map(float,array))




#sess.run(train_step, feed_dict={xs: batch_xs, ys: afterlist, keep_prob: 0.5})

print(compute_accuracy(testPixmaps, afterlist1))

InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_3' with dtype float
	 [[Node: Placeholder_3 = Placeholder[dtype=DT_FLOAT, shape=[], _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Caused by op u'Placeholder_3', defined at:
  File "/Users/DerekWang/anaconda/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/DerekWang/anaconda/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 442, in start
    ioloop.IOLoop.instance().start()
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 162, in start
    super(ZMQIOLoop, self).start()
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/tornado/ioloop.py", line 883, in start
    handler_func(fd_obj, events)
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 391, in execute_request
    user_expressions, allow_stdin)
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 199, in do_execute
    shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2723, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2825, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-187163350cce>", line 41, in <module>
    xs = tf.placeholder(tf.float32, [None, 784]) # 28x28
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 895, in placeholder
    name=name)
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1238, in _placeholder
    name=name)
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 704, in apply_op
    op_def=op_def)
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2260, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/DerekWang/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1230, in __init__
    self._traceback = _extract_stack()
